-- Estrutura do banco AcompanharDb (espelha o modelo EF Core em Acompanhar/Data/AcompanharContext.cs)
-- Executado automaticamente pelo container postgres na primeira inicialização (/docker-entrypoint-initdb.d).

CREATE TABLE "Administrador" (
    "Id"    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Email" text NULL,
    "Senha" text NULL
);

CREATE TABLE "Professor" (
    "Id"    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nome"  text NULL,
    "Email" text NULL,
    "Senha" text NULL
);

CREATE TABLE "Questionario" (
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Tema"        text NULL,
    "ProfessorId" integer NOT NULL,
    CONSTRAINT "FK_Questionario_Professor_ProfessorId" FOREIGN KEY ("ProfessorId")
        REFERENCES "Professor" ("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_Questionario_ProfessorId" ON "Questionario" ("ProfessorId");

CREATE TABLE "Questao" (
    "Id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Enunciado"      text NULL,
    "Justificativa"  text NULL,
    "QuestionarioId" integer NOT NULL,
    CONSTRAINT "FK_Questao_Questionario_QuestionarioId" FOREIGN KEY ("QuestionarioId")
        REFERENCES "Questionario" ("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_Questao_QuestionarioId" ON "Questao" ("QuestionarioId");

CREATE TABLE "Alternativa" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Rotulo"     text NULL,
    "Afirmacao"  text NULL,
    "Veracidade" boolean NOT NULL,
    "QuestaoId"  integer NOT NULL,
    CONSTRAINT "FK_Alternativa_Questao_QuestaoId" FOREIGN KEY ("QuestaoId")
        REFERENCES "Questao" ("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_Alternativa_QuestaoId" ON "Alternativa" ("QuestaoId");

CREATE TABLE "Tarefa" (
    "Id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Messagem"       text NULL,
    "Nota"           double precision NOT NULL,
    "QuestionarioId" integer NOT NULL,
    CONSTRAINT "FK_Tarefa_Questionario_QuestionarioId" FOREIGN KEY ("QuestionarioId")
        REFERENCES "Questionario" ("Id") ON DELETE CASCADE
);
CREATE INDEX "IX_Tarefa_QuestionarioId" ON "Tarefa" ("QuestionarioId");

-- Administrador inicial (a app busca o Id 1 / o primeiro registro para login e edição).
-- Troque a senha pela tela "Editar Administrador" após o primeiro acesso.
INSERT INTO "Administrador" ("Id", "Email", "Senha") VALUES (1, 'admin@acompanhar.com', 'admin');
SELECT setval(pg_get_serial_sequence('"Administrador"', 'Id'), 1);
